/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM
    id("org.jetbrains.kotlin.jvm").version("1.3.20")
    `maven-publish`
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven("https://jitpack.io")
}

version = "0.0.1-SNAPSHOT"
group = "org.vince.data2viz.ext"

dependencies {
    // Use the Kotlin JDK 8 standard library
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation("io.data2viz:d2v-data2viz-jfx:0.7.2-RC1")
    implementation("io.data2viz:d2v-data2viz-common:0.7.2-RC1")
    implementation("io.data2viz:d2v-axis-jfx:0.7.2-RC1")

    implementation("com.github.thomasnield:kotlin-statistics:1.2.1")
}



publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.vince.data2viz.ext"
            artifactId = "data2viz-ext"
            version = "0.0.1-SNAPSHOT"

            from(components["java"])
        }
    }
}

